- .changelog
- src/scss/base/typography/_mixins.scss
- src/site/blog.html
- src/site/resources.html
- src/site/testimonials.html
Fixes accessiblity for blog, resource and testimonial listings.
1. Uses the `reversed` attribute on the `<ol>` so that it’s clear that the first in the list isn’t the first that was added
2. Uses [Scott O’Hara’s method](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html) of fixing lists with `list-style: none`
This will close #97
> List order fixes

- .changelog
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/base/_reset.scss
- src/scss/base/typography/_general.scss
- src/scss/base/typography/_links.scss
- Makes `<small>` text a different style rather than smaller
- Amends colours in both light and dark mode, including highlight panels, to meet AAA colour contrast
- Stops silly link underline removal in reset, then subsequent re-addition in the link stylesheet
> Brings colour contrast to AAA

- .changelog
- src/js/link-buttons.js
- src/scss/base/_buttons.scss
- src/site/_includes/call-to-action.html
- src/site/_layouts/base.html
- Makes links with a role of button actionable with `space` as well as `return`
- Stops links that look like buttons being draggable with the `draggable="false"` attribute
- Removes button focus styling when active to stop messiness on Firefox
> Button accessibility fixes

- .changelog
- src/scss/base/typography/_mixins.scss
- src/scss/components/_call-to-action.scss
- src/site/_layouts/home.html
- src/site/about.md
- src/site/blog.html
- src/site/category.html
- src/site/feeds/feeds.json
- src/site/index.html
- src/site/posts/2017-11-11--a-shift-in-focus.md
- src/site/posts/2018-12-13--leaving-the-frontend-ne-meet-up.md
- src/site/posts/2019-01-02--a-new-years-resolution-for-2019.md
- src/site/posts/2019-06-14--implicit-aria-landmarks.md
- src/site/posts/2019-06-26--getting-to-grips-with-git.md
- src/site/posts/2019-07-02--design-and-dev-should-be-more-joined-up.md
- src/site/testimonials/martin-deane.md
- src/site/testimonials/ryan-davies.md
- Reduces main heading (`<h1>`) size slightly
- Uses 'development' rather than 'dev' in homepage `<h1>`
- Removes hyphen from references to frontend development
> h1 size reduction, homepage h1 tweak and 'front-end' to 'frontend'

- .changelog
- src/site/_includes/call-to-action.html
- src/site/_includes/newsletter-signup.html
- Makes contact CTA a bit less corporate sounding
- Reduces unsubscribe message in newsletter sign up small print
> Calls to action wording tweaks

- .changelog
- src/site/case-studies/case-studies.json
- src/site/feeds/atom.html
- src/site/feeds/json.html
- src/site/posts/2020-06-30--front-end-frontend-or-front-end.md
- src/site/posts/posts.json
- src/site/resources/resources.json
- src/site/testimonials/testimonials.json
- Allows post/resource/testimonial/case study URL override parameter in front matter
- Inserts non-breaking space into recent article title to fix problematic wrapping
- Removes non breaking spaces (which aren't valid) from titles in feeds
- Strips non breaking spaces from post/resource/testimonial/case study permalinks
> Post permalink filter and override

- .changelog
- package-lock.json
- package.json
- src/site/_data/site.json
- src/site/case-studies/case-studies.json
- src/site/feeds/atom.html
- src/site/feeds/json.html
- src/site/posts/2020-06-30--front-end-frontend-or-front-end.md
- src/site/posts/posts.json
- src/site/resources/resources.json
- src/site/testimonials/testimonials.json
- Allows post/resource/testimonial/case study URL override parameter in front matter
- Inserts non-breaking space into recent article title to fix problematic wrapping
- Removes non breaking spaces (which aren't valid) from titles in feeds
- Strips non breaking spaces from post/resource/testimonial/case study permalinks
> Release version 5.11.1

- .changelog
- src/scss/components/_content.scss
- src/scss/components/_footer.scss
- src/scss/components/_header.scss
- src/scss/legacy/_ie.scss
- src/scss/legacy/_print.scss
- src/site/_includes/footer.html
- src/site/_includes/header.html
- src/site/_includes/newsletter-signup.html
- src/site/_layouts/base.html
- Styles `header`, `navigation`, `main` and `footer` elements rather than their equivalent ARIA roles
- Removes `aria-hidden` attribute where there's already a `hidden` attribute
- Removes explicit ARIA roles of `banner`, `navigation`, `main` and `contentinfo`
> Removes explicit ARIA landmark roles

- .changelog
- src/scss/admin/_variables.scss
- src/scss/base/typography/_code.scss
- src/scss/base/typography/_links.scss
- Uses lighter background for code in light mode
- Addresses colour contrast for inline code inside links
- Tidies focus styling for inline code inside links
- Fixes colour contrast for syntax highlighted code in both light and dark modes
> Code colour contrast fixes

- .changelog
- package-lock.json
- package.json
- src/scss/admin/_mixins.scss
- src/site/_data/site.json
- src/site/_includes/footer.html
- Gives footer address a different role – presentation rather than group
- Removes navigation link dividers
- Gives navigation links a minimum height to be better touch targets
> Release version 5.11.9

- .changelog
- src/scss/base/typography/_links.scss
- Tweaks top padding on code in links
- Matches code in links' colours to rest of link
- Makes link text black on focus in Dark Mode, passing AA colour contrast
> Focus text colour contrast fixes

- netlify.toml
Netlify doesn't support wildcard filename redirects yet, so `*.sql`, etc. don't work
> Removes filepath wildcards as not supported

- .changelog
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/components/_logo.scss
- src/scss/components/_page.scss
- lightens logo underscore
- Changes 'light' Light Mode colour variable to 'lightest' and introduces new 'light'
- Uses original brand blue for top and bottom strips
- Fixes scrollbar colour in Light Mode so that it's dark against the white background instead of white
> Light mode scrollbar fix and some colour modifications

- .changelog
- src/site/_includes/more-posts.html
- src/site/_layouts/home.html
- src/site/testimonials.html
- Uses `aria-labelledby` instead of `aria-label` for sections where appropriate
- Uses same text testimonial 'read more' visually and programmatically
> `aria-label` audit for sections and read more

- src/site/posts/2021-02-04--choosing-a-stash-from-the-list.md
- src/site/posts/2021-02-08--applying-a-git-stash-non-destructively.md
- Fixes mixed up tense in `git stash apply` post
- Links to `git stash save` post from `git stash list` post (as the 'save' post wasn't live when the 'list' post was published)
> A couple of git stash edits, including linking between two articles

- .changelog
- src/scss/base/typography/_links.scss
- src/scss/components/_skip-to-content.scss
- Adds focus outline to links, consistent with form focus styling
- Adds focus outline to 'skip to main content' link, consistent with other focus styling
> Link focus styling

- .changelog
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/base/_buttons.scss
- src/scss/base/_forms.scss
- src/scss/base/typography/_general.scss
- src/scss/base/typography/_links.scss
- src/scss/components/_logo.scss
- src/scss/components/_page.scss
- Renames lightest Light Mode colour variable to be consistent with Dark Mode
- Lightens Light Mode hightlight colour slightly
- Uses `colour-primary` for every default state in Light Mode
- Simplifies `::selection` colours
- Simplifies hidden page background colour styling
- All Dark Mode hover states lighten the blue
- Removes unused `colour-primary-light` colour variable
> Colour consistency and simplification

- .changelog
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/base/_buttons.scss
- src/scss/base/_forms.scss
- src/scss/base/_reset.scss
- src/scss/base/typography/_code.scss
- src/scss/base/typography/_general.scss
- src/scss/base/typography/_links.scss
- src/scss/base/typography/_mixins.scss
- src/scss/components/_footer.scss
- src/scss/components/_logo.scss
- src/scss/components/_page.scss
- src/scss/components/_skip-to-content.scss
- Creates new main colour variable for consistency with Dark Mode colour palette
- Adds anti-aliasing to dark mode text
- Adds high contrast mode
- Uses `colour-` prefix for `$black` colour variable
- Uses `colour-` prefix for `$white` colour variable
- Renames `$colour-primary-highlight` to `$colour-highlight`
- Corrects spelling of 'colour' in dark mode mixin
- Makes scroll markers in light mode dark again
- Removes letter spacing in dark mode to fix multi-word link underlines
- Fixes spacing inconsistency with `@includes`
- Tidies up Dark Mode @includes
> High contrast colour scheme

- .changelog
- package-lock.json
- package.json
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/base/_buttons.scss
- src/scss/base/_forms.scss
- src/scss/base/_reset.scss
- src/scss/base/typography/_code.scss
- src/scss/base/typography/_general.scss
- src/scss/base/typography/_links.scss
- src/scss/base/typography/_mixins.scss
- src/scss/components/_footer.scss
- src/scss/components/_logo.scss
- src/scss/components/_page.scss
- src/scss/components/_skip-to-content.scss
- src/site/_data/site.json
- Creates new main colour variable for consistency with Dark Mode colour palette
- Adds anti-aliasing to dark mode text
- Adds high contrast mode
- Uses `colour-` prefix for `$black` colour variable
- Uses `colour-` prefix for `$white` colour variable
- Renames `$colour-primary-highlight` to `$colour-highlight`
- Corrects spelling of 'colour' in dark mode mixin
- Makes scroll markers in light mode dark again
- Removes letter spacing in dark mode to fix multi-word link underlines
- Fixes spacing inconsistency with `@includes`
- Tidies up Dark Mode @includes
> Release version 5.16.0

- .changelog
- src/scss/admin/_mixins.scss
- src/scss/base/_buttons.scss
- src/scss/base/_tables.scss
- src/scss/base/typography/_links.scss
- `:focus-visible` enhancement for links
- `:focus-visible` enhancement for buttons
- `:focus-visible` enhancement for tables
- Removes button focus combination styles (focus + hover, focus + active)
- Removes unnecessary text underline styling removal for link-button focus
> Adds focus-visible where appropriate, for tidier focus styles

- .changelog
- package-lock.json
- package.json
- src/scss/base/_tables.scss
- src/scss/base/typography/_code.scss
- src/scss/base/typography/_links.scss
- src/scss/components/_footer.scss
- src/site/_data/site.json
- Uses `math.div()` syntax for division in Sass, ready for Dart Sass 2.0.0
> Release version 5.16.6

- .changelog
- package-lock.json
- src/scss/admin/_mixins.scss
- src/scss/admin/_variables.scss
- src/scss/base/_buttons.scss
- src/scss/base/typography/_links.scss
- New lighter blue for High Contrast
- Lightens blue on hover in High Contrast Mode
- Removes an unused `reverse-list-marker` mixin
> Increases contrast on hover in High Contrast mode

- .changelog
- src/scss/base/_utility--critical.scss
- src/scss/base/_utility--non-critical.scss
- src/scss/critical.scss
- src/scss/non-critical.scss
- src/site/_layouts/home.html
- src/site/testimonials.html
- Removes 'Read more' link from testimonials
- Uses `<ul>` rather than `<ol>` for featured blog posts
- Moves post in list styling to critical CSS to stop layout shift
- Adds index list marker removal to critical CSS to stop flash
> Stops some flashes by moving styles to critical CSS

- .changelog
- package-lock.json
- package.json
- src/scss/base/_utility--critical.scss
- src/scss/base/_utility--non-critical.scss
- src/scss/critical.scss
- src/scss/non-critical.scss
- src/site/_data/site.json
- src/site/_layouts/home.html
- src/site/testimonials.html
- Removes 'Read more' link from testimonials
- Uses `<ul>` rather than `<ol>` for featured blog posts
- Moves post in list styling to critical CSS to stop layout shift
- Adds index list marker removal to critical CSS to stop flash
> Release version 6.0.3

- .changelog
- package-lock.json
- package.json
- src/scss/base/_page.scss
- src/site/_data/site.js
- src/site/_layouts/base.html
- Removes unnecessary `.canvas` and `.page-wrapper` elements, now that Safari doesn't show background colour on scroll bounce
- Removes hidden horizontal scroll from page
- Removes scroll bounce colour for Chrome and Firefox on macOS
> Removes scroll bounce background colour

- .changelog
- .eleventy.js
- package-lock.json
- package.json
- src/site/_data/site.js
- src/site/_includes/call-to-action.html
- src/site/_includes/head.html
- src/site/_includes/more-posts.html
- src/site/_includes/post-categories.html
- src/site/_includes/post-in-list.html
- src/site/case-studies/case-studies.json
- src/site/category.html
- src/site/portfolio.html
- src/site/posts/2012-04-27--dropbox-my-most-useful-app.md
- src/site/posts/2019-08-04--website-version-5.md
- src/site/posts/posts.json
- src/site/resources/2019-11-25--hero-images-pros-and-cons.md
- src/site/resources/resources.json
- src/site/skills/skills.json
- src/site/testimonials/testimonials.json
- Updates to Eleventy 1.0
- Uses `slugify` filter instead of `slug`
- Removes `eleventyConfig.setDataDeepMerge(true)`
- Removes markdown-it dependency as it's in Eleventy already
- Fixes case study tag with underline
- Uses post-in-list template for case studies
> Updates to Eleventy 1.0

- .changelog
- package-lock.json
- package.json
- src/scss/admin/mixins/_buttons.scss
- src/scss/admin/mixins/_general.scss
- src/scss/admin/mixins/_links.scss
- src/scss/base/_forms.scss
- src/scss/base/_reset.scss
- src/scss/critical.scss
- src/scss/non-critical.scss
- src/site/_data/site.js
- Gives links their own SCSS file
- Uses `outline` for link focus styling, rather than `box-shadow`
- Uses `outline` for button focus styling, rather than `box-shadow`
- Uses `outline` for input focus styling, rather than `box-shadow`
> Focus outline refactor

- src/site/posts/2024-04-23--images-as-the-first-thing-in-a-button-or-link.md
Fix unclosed `src` property on image tag example.
> Fixing minor missing closing quotes in example code -2024-04-23--images-as-the-first-thing-in-a-button-or-link.md
